// <auto-generated />
using System;
using System.Collections.Generic;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190710150057_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("BusinessLogic.Entry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Addition");

                    b.Property<string>("Caption");

                    b.Property<bool>("IsDone");

                    b.Property<string>("Link");

                    b.Property<int?>("PadId");

                    b.Property<List<string>>("Tags");

                    b.HasKey("Id");

                    b.HasIndex("PadId");

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("BusinessLogic.Pad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ActivePageIndex");

                    b.Property<int>("ActiveTaskIndex");

                    b.HasKey("Id");

                    b.ToTable("Pads");
                });

            modelBuilder.Entity("BusinessLogic.Entry", b =>
                {
                    b.HasOne("BusinessLogic.Pad", "Pad")
                        .WithMany("Entries")
                        .HasForeignKey("PadId");
                });
#pragma warning restore 612, 618
        }
    }
}
