// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20191105215257_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BusinessLogic.Pad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ActivePageIndex");

                    b.Property<int>("ActiveTaskIndex");

                    b.Property<bool>("TaskWasStartedThisTurn");

                    b.HasKey("Id");

                    b.ToTable("Pads");
                });

            modelBuilder.Entity("BusinessLogic.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Addition");

                    b.Property<string>("Caption");

                    b.Property<bool>("IsDone");

                    b.Property<string>("Link");

                    b.Property<int?>("PadId");

                    b.HasKey("Id");

                    b.HasIndex("PadId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("BusinessLogic.Task", b =>
                {
                    b.HasOne("BusinessLogic.Pad", "Pad")
                        .WithMany("Tasks")
                        .HasForeignKey("PadId");
                });
#pragma warning restore 612, 618
        }
    }
}
